### ISSUE TITLE
Youtube API v2 deprecated

### ISSUE THREAD

**Issue by kipsigman** [lunametrics/youtube-google-analytics#20]
Because YouTube API v2 is now deprecated, all results for videoTitle are returning the string "https://youtube.com/devicesupport." This can be fixed by upgrading the library to YouTube data API v3 - https://developers.google.com/youtube/v3/. Users will have to probably set an API key when using this library once upgraded to this new version.

**Comment by DanWilkerson** [comment]
Hi Kip,

We updated the script with a new version to fix that issue; we're
interested in consistent and simple data collection, so we've opted to
forgo the Title altogether and let users add it back in either using Lookup
Tables or Data Import.

Dan

**Comment by kipsigman** [comment]
Thanks Dan, that sounds like a sensible alternative.
