### ISSUE TITLE
% tracked for related videos

### ISSUE THREAD

**Issue by cforella** [lunametrics/youtube-google-analytics#21]
The % tracked events fire only for the primary embedded video. If the user watches the video to the end and click on a related video, only the Play, Pause, Watch to End and other related events are pushed to the data layer by Tag Manager, but not the % watched. It would be useful to track the % watched in all videos that the user watches.

**Comment by DanWilkerson** [comment]
Should be fixed with eee4c0c6885acead10cb3f65ac67ff833c2697fb
