### ISSUE TITLE
Keep filename consistent

### ISSUE THREAD

**Issue by jevy** [lunametrics/youtube-google-analytics#25]
Hi @DanWilkerson,

I'm going to add you to http://www.jsdelivr.com.  Would you be cool keeping the filename consistent so the file will auto-update for users?  Love this library.

**Comment by jevy** [comment]
Oops just realized it won't qualify:

> It requires github/npm/bower with tagged versions. - https://github.com/jsdelivr/jsdelivr

**Comment by DanWilkerson** [comment]
Neat; I'll take a look at if we can do this.
