### ISSUE TITLE
Making events available for use before being sent off to GA

### ISSUE THREAD

**Issue by HazelGrant** [lunametrics/youtube-google-analytics#29]
Hi,

I have been working on pulling Video event information into my application for my own use. I have experimented with two ways of doing so - pulling the information from Google Analytics after this library has sent it there, and pulling the information before it gets sent. I like pulling the information before it gets sent better - fewer API calls. I've been tweaking your library so that I can pull tracking data from the library for use in my application, and was wondering if you might welcome a pull request which adds the ability for everyone who uses this library to do so. It may be outside the scope of this project, but I've been working on the code anyway so I thought I would pass it by you.

Thank you for this library - it's been amazingly helpful and working with it has taught me quite a lot about how to interact with both YouTube and Google Analytics.

Have a good afternoon!

**Comment by DanWilkerson** [comment]
Definitely interested. I'll have to discuss internally to see if we think that's outside the scope of this library, but I think having a solution that decouples Analytics from the YouTube events directly is a great idea.
