### ISSUE TITLE
Error in GTM when importing JSON

### ISSUE THREAD

**Issue by theappgeeks** [lunametrics/youtube-google-analytics#33]
I am following the Instructions in the Container Import (recommended) section of the installation guide. When I Import the luna-youtube-tracking.json file into GTM, it fails on Step 7 "Click Continue, then Confirm". It can't proceed as GTM says "the file format is invalid" and JSON parsing error: no viable alternative at input '"en"'. See screenshot. Thanks

![2016-01-03_20-35-31](https://cloud.githubusercontent.com/assets/16529510/12080676/0c463b42-b25a-11e5-81ae-441f492447c2.png)

**Comment by DanWilkerson** [comment]
@theappgeeks Looks like you may have saved the HTML instead of the JSON file - that's the markup for the GitHub viewer of the code itself. Try downloading the repo in zip format and accessing the file there, or opening the raw version of the file and copy+pasting it into a new file.
