### ISSUE TITLE
Please choose a software license (not a Creative Commons license)

### ISSUE THREAD

**Issue by jeffreybarke** [lunametrics/youtube-google-analytics#40]
My concern is that I'm not clear what the attribution requirement means for software.

I would go with an MIT license for this particular project:
https://opensource.org/licenses/MIT

Note that Creative Commons does not recommend using their licenses for software:
https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

**Comment by DanWilkerson** [comment]
Thanks for pointing this out! We'll switch the license to something more sensible.

**Comment by DanWilkerson** [comment]
https://github.com/lunametrics/youtube-google-analytics/commit/54a47168c401d35405754fa65a7d05792d200940
