### ISSUE TITLE
Mixed content HTTP/HTTPS

### ISSUE THREAD

**Issue by jantoine1** [lunametrics/youtube-google-analytics#8]
When using the library within a page loaded via HTTPS, Firefox would display the following error message:

> Blocked loading mixed active content
> This is because line 183 of the lunametrics-youtube-v6.js file hardcodes the http protocol in the URL used for retrieving video data rather than using the protocol used for the current page request. The following stackoverflow.com article pointed to simply removing the protocol from the URL, and this worked in my case:
> http://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire

**Comment by kipsigman** [comment]
I came across the same issue, as my page is displayed on HTTPS. I changed the line to use "https", but I like the solution of removing the protocol better. This would be a great quick fix in the next version of the library.

P.S. Thanks for this lib, it saved me a lot of work!
